# Generated by Django 5.2.6 on 2025-09-30 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_id",
                    models.BigIntegerField(
                        help_text="The unique ID of the topic/thread in Telegram. Used for sending messages to the topic.",
                        unique=True,
                        verbose_name="Topic ID (message_thread_id)",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        help_text="The ID of the Telegram Supergroup (Forum) that contains this topic.",
                        verbose_name="Supergroup Chat ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Topic Name")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Topic",
                "verbose_name_plural": "Forum Topics",
                "unique_together": {("topic_id", "chat_id")},
            },
        ),
    ]
