# Generated by Django 5.2.6 on 2025-10-05 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forumtopic",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="forumtopic",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="is_full",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="forumtopic",
            name="chat_id",
            field=models.BigIntegerField(verbose_name="Telegram Supergroup Chat ID"),
        ),
        migrations.AlterField(
            model_name="forumtopic",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="forumtopic",
            name="topic_id",
            field=models.BigIntegerField(unique=True, verbose_name="Telegram Topic ID"),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="group",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="telegram_bot.group",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "group")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_groups",
                through="telegram_bot.GroupMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
