# Generated by Django 5.2.6 on 2025-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_telegramprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumtopic",
            name="chat_id",
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="Telegram Group ID"
            ),
        ),
    ]
