# Generated by Django 5.2.6 on 2025-10-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0004_remove_forumtopic_chat_id_alter_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="member_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="telegram_invite_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
