# Generated by Django 5.2.6 on 2025-10-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0005_group_member_count_group_telegram_invite_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="created_by",
        ),
        migrations.AddField(
            model_name="group",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
