# Generated by Django 5.2.6 on 2025-10-09 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0006_remove_group_created_by_group_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
