# Generated by Django 5.2.6 on 2025-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0007_group_updated_at_telegramprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumtopic",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
