# Generated by Django 5.2.6 on 2025-10-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0008_alter_forumtopic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumtopic",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="forumtopic",
            unique_together={("group", "topic_id")},
        ),
    ]
