# Generated by Django 5.2.6 on 2025-10-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0009_alter_forumtopic_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="forumtopic",
            unique_together={("group", "name")},
        ),
    ]
