# Generated by Django 5.2.6 on 2025-12-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0010_alter_forumtopic_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="group",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="group",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="group",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="group",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="group",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="telegram_bot.groupcategory",
            ),
        ),
    ]
