# Generated by Django 5.2.6 on 2025-12-13 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0012_group_created_at_group_is_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="telegram_group_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram Group ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="category",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="telegram_bot.groupcategory",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="groupcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
